from __future__ import annotations

from typing import Any, ClassVar, Optional, Sequence, Tuple, Iterable
import numpy as np
from numpy.typing import NDArray
from astropy.io import fits

# Auto-generated by gen_pyi.py. DO NOT EDIT BY HAND.

# Constants (from __init__.py)
GRAVITY_FT: int
GRAVITY_FT_P1: int
GRAVITY_FT_P2: int
GRAVITY_SC: int
GRAVITY_SC_P1: int
GRAVITY_SC_P2: int
__version__: str

class HDUModel:
    EXTNAME: ClassVar[str]
    COLUMNS: ClassVar[Sequence[Tuple[str, bool]]]
    header: dict[str, Any]
    extver: Optional[int]
    insname: Optional[str]
    arrname: Optional[str]
    def __init__(
        self,
        hdul: fits.HDUList,
        extver: Optional[int] = ...,
        header_keys: Optional[list[str]] = ...,
    ) -> None: ...
    def _post_decode(self) -> None: ...
    def __repr__(self) -> str: ...

# HDUModel subclasses (generated from COLUMNS)
class OI_ARRAY(HDUModel):
    EXTNAME: ClassVar[str]
    COLUMNS: ClassVar[Sequence[Tuple[str, bool]]]
    sta_index: NDArray[Any]
    sta_name: NDArray[Any]
    staxyz: NDArray[Any]
    tel_name: Optional[NDArray[Any]]
    diameter: Optional[NDArray[Any]]
    fov: Optional[NDArray[Any]]
    fovtype: Optional[NDArray[Any]]

class OI_FLUX(HDUModel):
    EXTNAME: ClassVar[str]
    COLUMNS: ClassVar[Sequence[Tuple[str, bool]]]
    sta_index: NDArray[Any]
    mjd: NDArray[Any]
    flag: NDArray[Any]
    flux: NDArray[Any]
    fluxerr: NDArray[Any]

class OI_T3(HDUModel):
    EXTNAME: ClassVar[str]
    COLUMNS: ClassVar[Sequence[Tuple[str, bool]]]
    mjd: NDArray[Any]
    sta_index: NDArray[Any]
    u1coord: NDArray[Any]
    v1coord: NDArray[Any]
    u2coord: NDArray[Any]
    v2coord: NDArray[Any]
    flag: NDArray[Any]
    t3phi: NDArray[Any]
    t3phierr: NDArray[Any]
    t3amp: Optional[NDArray[Any]]
    t3amperr: Optional[NDArray[Any]]

class OI_VIS(HDUModel):
    EXTNAME: ClassVar[str]
    COLUMNS: ClassVar[Sequence[Tuple[str, bool]]]
    mjd: NDArray[Any]
    sta_index: NDArray[Any]
    ucoord: NDArray[Any]
    vcoord: NDArray[Any]
    flag: NDArray[Any]
    visdata: NDArray[Any]
    viserr: NDArray[Any]
    visamp: NDArray[Any]
    visamperr: NDArray[Any]
    visphi: Optional[NDArray[Any]]
    visphierr: Optional[NDArray[Any]]

class OI_WAVELENGTH(HDUModel):
    EXTNAME: ClassVar[str]
    COLUMNS: ClassVar[Sequence[Tuple[str, bool]]]
    eff_wave: NDArray[Any]
    eff_band: Optional[NDArray[Any]]

# OI aggregate container
class OI:
    array: OI_ARRAY
    wavelength: OI_WAVELENGTH
    flux: OI_FLUX
    vis: OI_VIS
    t3: OI_T3
    extver: int
    @classmethod
    def load(cls, hdul: fits.HDUList, extver: int) -> OI: ...

